spring:
  main:
    allow-bean-definition-overriding: true
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
      url: jdbc:h2:mem:fazendario
      driver-class-name: org.h2.Driver
      username: sa
      password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

javers:
  algorithm: simple
  auditable-objects-scanner: spring
  mongodb:
    uri: mongodb://admin:123@localhost:27017/fazendario?authSource=admin
  mappingStyle: FIELD
  commitIdGenerator: synchronized_sequence
  prettyPrint: true
  typeSafeValues: false
  initialChanges: true
  terminalChanges: true

logging:
  level:
    org.javers: DEBUG
