spring:
  main:
    allow-bean-definition-overriding: true
    datasource:
      url: jdbc:h2:mem:fazendario
      driver-class-name: org.h2.Driver
      username: sa
      password:
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      database-platform: org.hibernate.dialect.H2Dialect

  data:
    mongodb:
      authentication-database: admin
      auto-index-creation: true
      host: localhost
      port: 27017
      database: auditoria
      username: admin
      password: 123


