spring:
  main:
    allow-bean-definition-overriding: true
    datasource:
      url: jdbc:h2:mem:fazendario
      driver-class-name: org.h2.Driver
      username: sa
      password:
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      database-platform: org.hibernate.dialect.H2Dialect

    data:
      mongodb:
        uri: mongodb://localhost:27017/javers-auditoria
        username: root
        password: root
        authentication-database: admin


